name: Deploy to VPS

on:
  push:
    branches: [main]
    paths:
      - 'vps/**'
      - 'mt5_bridge_service/**'
      - '.github/workflows/deploy-vps.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Windows VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          timeout: 60s
          command_timeout: 30m
          script: |
            echo "Starting VPS deployment..."
            cd C:\mt5_bridge_service
            
            echo "Killing any existing Python processes on port 8000..."
            powershell -Command "Get-Process python -ErrorAction SilentlyContinue | Stop-Process -Force"
            Start-Sleep -Seconds 3
            
            echo "Freeing port 8000..."
            powershell -Command "$proc = Get-NetTCPConnection -LocalPort 8000 -ErrorAction SilentlyContinue | Select-Object -ExpandProperty OwningProcess -Unique; if ($proc) { Stop-Process -Id $proc -Force }"
            Start-Sleep -Seconds 2
            
            echo "Pulling latest code from GitHub..."
            git pull origin main
            
            echo "Starting MT5 Bridge API Service..."
            Start-Process -FilePath "python" -ArgumentList "mt5_bridge_api_service.py" -WindowStyle Hidden -RedirectStandardOutput "logs\service.log" -RedirectStandardError "logs\service_error.log"
            
            Start-Sleep -Seconds 10
            
            echo "Verifying service is running..."
            powershell -Command "Invoke-WebRequest -Uri http://localhost:8000/api/mt5/bridge/health -UseBasicParsing -TimeoutSec 5 | Select-Object -ExpandProperty StatusCode"
            
            echo "Deployment complete!"
      
      - name: Verify Deployment
        run: |
          echo "✅ VPS deployment triggered successfully"
          echo "📊 Check VPS logs for deployment status"
          echo "🔍 Verify at: C:\mt5_bridge_service\logs\auto_update.log"
