name: Deploy to VPS

on:
  push:
    branches: [main]
    paths:
      - 'vps/**'
      - 'mt5_bridge_service/**'
      - '.github/workflows/deploy-vps.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Windows VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          timeout: 60s
          command_timeout: 30m
          script: |
            echo "🚀 Starting VPS deployment..."
            cd C:\mt5_bridge_service
            powershell -ExecutionPolicy Bypass -File auto_update.ps1
            echo "✅ Deployment complete!"
      
      - name: Verify Deployment
        run: |
          echo "✅ VPS deployment triggered successfully"
          echo "📊 Check VPS logs for deployment status"
          echo "🔍 Verify at: C:\mt5_bridge_service\logs\auto_update.log"
